services:
    app:
      build: .
      env_file:
         - .env
      ports:
         - "5000:5000"
      depends_on:
         - db
      networks:
         - backend

    db:
     image: postgres:14
     restart: always
     env_file:
               - .env
     environment:
       POSTGRES_DB: mydatabase
       POSTGRES_USER: venkat
       POSTGRES_PASSWORD: 1234
     volumes:
       - pgdata:/var/lib/postgresql/data
     networks:
       - backend

volumes:
    pgdata:
networks:
    backend:
